

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_40 = Integer(40); _sage_const_16 = Integer(16)
from Crypto.Util.Padding import pad, unpad
from Crypto.Util.number import long_to_bytes, bytes_to_long
from Crypto.Cipher import AES
from hashlib import sha256
import base64
import re

with open('output.txt', 'r') as f:
    lines = f.readlines()

N = _sage_const_7 

curves = [None for _ in range(N)]
g = [None for _ in range(N)]
S_pub = [None for _ in range(N)]
R_pub = [None for _ in range(N)]
encrypted_msg = [None for _ in range(N)]

for i in range(N):
    a, b, p = re.findall(r'\d{2,}', lines[i*_sage_const_4 +_sage_const_0 ])
    a = int(a)
    b = int(b)
    p = int(p)
    E = EllipticCurve(GF(p), [a, b])
    curves[i] = E
    exec(lines[i*_sage_const_4 +_sage_const_1 ])
    exec(lines[i*_sage_const_4 +_sage_const_2 ])
    exec(lines[i*_sage_const_4 +_sage_const_3 ])
    g[i] = E(g[i])
    S_pub[i] = E(S_pub[i])
    R_pub[i] = E(R_pub[i])

moduli = []
residues = []
for idx, curve in enumerate(curves):
    n = curve.order()
    fac = list(factor(n))
    for i, j in fac:
        modules = i**j
        if i > _sage_const_1  << _sage_const_40 :
            break
        _g_ = g[idx]*ZZ(n/modules)
        _q_ = S_pub[idx]*ZZ(n/modules)
        residue = discrete_log(_q_, _g_, operation="+")
        moduli.append(modules)
        residues.append(residue)
        print(residue, modules)

secret = crt(residues, moduli)
encrypted_msg = [None]
exec(lines[_sage_const_4 *N])
px = (R_pub[_sage_const_0 ]*secret).xy()[_sage_const_0 ]
_hash = sha256(long_to_bytes(px)).digest()
key = _hash[:_sage_const_16 ]
iv = _hash[_sage_const_16 :]
msg = AES.new(key, AES.MODE_CBC, iv).decrypt(base64.b64decode(encrypted_msg[_sage_const_0 ]))
msg = unpad(msg, _sage_const_16 )
print(msg)

